version: '3'

services:
  app: 
    build: .
    entrypoint: dockerize -wait tcp://db:3307 -timeout 40s ./.docker/entrypoint.sh
    container_name: api-app
    ports:
      - 5000:5000
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build:  ./.docker/mysql
    container_name: api-db
    ports:
      - 3307:3307
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fin
      - MYSQL_ROOT_PASSWORD=root

      